### ISSUE TITLE
EVAN PATCH ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/EI-SQL-PATCH#1]
1.RV 1 SHLD REMOVE PRETERMINATE FLAG =X ,
2.DEL THE AUTO TERMINATION COMMENTS.
3.NO NEED TO UPDATE COMMENTS REG RV 2 AND RV 3.

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
ABOVE ISSUE FIXED N DELIVERED.
