### ISSUE TITLE
UNIT SD DP SETTING WRONG DATE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/EI-SQL-PATCH#3]
**DEFECT OWNER: SQL TEAM**

IN DB UNIT SD =20/04/2015 nd in DT also it SD = 20/4/2015.
BUT AFTER CLICK SEARCH , SD =01/04/2015.

BCZ, SP RETURNING DATE FORM OWNER SHOWING IN THE DP.

UNIT HAS EXP 17/04/2015, AND ONE CUSTOMER HAS PAYMENT 01/04/2015.BUT PAYMENT ALWAYS WILL CHECK **MONTH/YEAR** NOT DD/MM/YYYY.

**FIX PAYMENT CHECKING WITH MM/YYYY**

**Comment by DHANDAPANISATTANATHAN** [comment]
DIV,

if we use PAID DATE fr Trans SP.We cannt handle the practical scenarios.

Like. Mansi sigh PAID deposit in 12
Proceed to chk PAID DATE fr Trans SP!
and then we ll change in Form side the Date to 11/4!

9999 is ok, as it is nt a real unit, its a dummy unit fr EXP!
2317 is also a normal unit like others, so this shd follow like other unit soly!

**Comment by DHIVYAARJUAN** [comment]
ABOVE ISSUE FIXED AND DELIVERED IN BELOW LINK
https://github.com/SSOMENSREPO/EI-HTML-SQL/releases/tag/v1.4

status :  **delivered**
